# Generated by Django 4.2 on 2026-01-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
