# Generated by Django 4.2 on 2026-01-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0003_chat_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tokens_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='tokens_out',
            field=models.IntegerField(default=0),
        ),
    ]
