# Generated by Django 4.2 on 2025-10-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0003_alter_message_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_message_per_chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
    ]
