# Generated by Django 4.2 on 2026-01-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0004_chat_tokens_in_chat_tokens_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='intent',
            field=models.TextField(default='NOT FOUND'),
        ),
    ]
