# Generated by Django 5.2.8 on 2026-08-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0007_chat_evaluation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='products_shown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
