# Generated by Django 5.2.8 on 2026-08-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0008_message_products_shown"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="flag_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chat",
            name="flag_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chat",
            name="flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="flagged_by",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="chat",
            name="github_issue_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="github_issue_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chat",
            name="investigation_status",
            field=models.CharField(
                choices=[
                    ("unflagged", "Unflagged"),
                    ("flagged", "Flagged"),
                    ("resolved", "Resolved"),
                ],
                default="unflagged",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="linear_issue_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="chat",
            name="linear_issue_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
