# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0009_chat_investigation_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightsSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField(unique=True)),
                ("payload", models.JSONField()),
                ("conversations_analyzed", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
    ]
