# Generated by Django 5.2.8 on 2026-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0010_insightssnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="cache_creation_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="cache_read_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
