# Generated by Django 5.2.8 on 2026-09-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0011_message_cache_creation_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="likely_automated",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
