# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0012_chat_likely_automated"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostMethodologyChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("measurement_fix", "Measurement fix"),
                            ("new_feature", "New feature"),
                            ("config_change", "Config change"),
                            ("incident", "Incident"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
