# Generated by Django 5.2.8
#
# Seeds CostMethodologyChange with the real, dated events this app's own git
# history (and shopify_chatbot_agent_2's) turned up while investigating a
# reported >100% month-over-month jump in "cost per conversation" -- so the
# new cost_commentary feature has real grounding data from day one instead
# of starting empty. See that investigation's writeup for full sourcing
# (git show / Linear / gh run list on each item).

from django.db import migrations

SEED_ENTRIES = [
    {
        "date": "2026-08-15",
        "category": "new_feature",
        "description": (
            "shopify_chatbot_agent_2: ENG-99 prompt-injection/manipulation-"
            "resistance block added to the chat system prompt (+3,754 bytes "
            "in one commit, ~26% of that prompt's total growth since "
            "2026-08-02) -- a real, modest, ongoing increase to the cached "
            "system-prompt token count."
        ),
    },
    {
        "date": "2026-08-31",
        "category": "new_feature",
        "description": (
            "shopify_chatbot_agent_2: the AI Search Curator went from 1 "
            "Claude call to 2 per page load (agentic query construction "
            "added ahead of the existing summary call, PR #342) -- a real "
            "doubling of LLM-call volume on that surface, landing on the "
            "last day of the prior comparison month."
        ),
    },
    {
        "date": "2026-09-16",
        "category": "measurement_fix",
        "description": (
            "shopify_chatbot_agent_2 (ENG-148) started sending "
            "cache_creation/cache_read token counts to this app's "
            "log_message endpoint; this app started storing and pricing "
            "them (migration 0011). Before this, every cache-hit chat turn's "
            "true cost was invisible here -- a real undercount, now "
            "corrected, not a real spend increase."
        ),
    },
    {
        "date": "2026-09-16",
        "category": "measurement_fix",
        "description": (
            "This app's own cost-estimate formula was rewritten several "
            "times in ~15 hours: hardcoded per-model pricing replaced with "
            "real Anthropic-billed rates; a whole-org spend total found to "
            "include ~$37/month from four unrelated Anthropic workspaces "
            "(Claude Code, BudgetETL, Photo Highlights, Roblox Studio), "
            "then scoped down to this app's own keys; a transient ~1500x "
            "cost-estimate bug (live ~20 minutes right after a key "
            "rotation) caught and reverted the same evening. None of this "
            "reflects a real change in Anthropic spend -- purely measurement "
            "accuracy converging on the true number."
        ),
    },
    {
        "date": "2026-09-17",
        "category": "measurement_fix",
        "description": (
            "A scripted bot pinging shopify_chatbot_agent_2's live chat "
            "endpoint every ~6 minutes for weeks (fresh chat_id each time) "
            "was excluded from this app's conversation counts (2,700+ "
            "flagged chats, ENG-149/150) and shopify_chatbot_agent_2 fixed "
            "session_start firing once per chat turn instead of once per "
            "conversation. Both mechanically raise cost/conversation by "
            "shrinking an inflated denominator back to the real "
            "conversation count -- not a real per-conversation cost "
            "increase."
        ),
    },
]


def seed_changes(apps, schema_editor):
    CostMethodologyChange = apps.get_model("cost_management", "CostMethodologyChange")
    for entry in SEED_ENTRIES:
        CostMethodologyChange.objects.get_or_create(
            date=entry["date"], description=entry["description"],
            defaults={"category": entry["category"]},
        )


def remove_seeded_changes(apps, schema_editor):
    CostMethodologyChange = apps.get_model("cost_management", "CostMethodologyChange")
    CostMethodologyChange.objects.filter(
        description__in=[e["description"] for e in SEED_ENTRIES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0013_costmethodologychange"),
    ]

    operations = [
        migrations.RunPython(seed_changes, remove_seeded_changes),
    ]
