# Generated by Django 5.2.8
#
# Seeds one more CostMethodologyChange entry (see 0014_seed_cost_methodology_
# changes.py for the pattern) documenting today's fix to cost_pc's own
# numerator -- the dashboard's "Cost / conversation" KPI was overstating
# spend by roughly the ENG-149/150 bot's share of traffic.

from django.db import migrations

SEED_ENTRIES = [
    {
        "date": "2026-09-17",
        "category": "measurement_fix",
        "description": (
            "cost_pc's numerator was billed spend for the chat surface's "
            "key(s), which still includes the ENG-149/150 bot's own "
            "traffic (it hits the same chat API key as real shoppers) -- "
            "while the denominator (`convs`) already excludes it. That "
            "mismatch overstated cost/conversation by roughly the bot's "
            "share of logged spend. Fixed by prorating a cost-weighted bot "
            "share (Chat/Message token counts priced via get_model_rates, "
            "not a raw token-count share -- cache reads bill at a steep "
            "discount and cache writes at a premium) out of the numerator "
            "before dividing. The 'Anthropic spend' KPI itself is "
            "unchanged -- the bot's cost was real money; only cost_pc's "
            "own numerator is adjusted."
        ),
    },
]


def seed_changes(apps, schema_editor):
    CostMethodologyChange = apps.get_model("cost_management", "CostMethodologyChange")
    for entry in SEED_ENTRIES:
        CostMethodologyChange.objects.get_or_create(
            date=entry["date"], description=entry["description"],
            defaults={"category": entry["category"]},
        )


def remove_seeded_changes(apps, schema_editor):
    CostMethodologyChange = apps.get_model("cost_management", "CostMethodologyChange")
    CostMethodologyChange.objects.filter(
        description__in=[e["description"] for e in SEED_ENTRIES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0014_seed_cost_methodology_changes"),
    ]

    operations = [
        migrations.RunPython(seed_changes, remove_seeded_changes),
    ]
