# Generated by Django 5.2.8
#
# ENG-164: flags every chat created by the AOP monitor's retired synthetic
# probe as likely_automated, so they drop out of the chat summary,
# conversation counts and insights. See cost_management/probe_chats.py. Also
# seeds a CostMethodologyChange entry, since removing these chats from the
# conversation count moves cost/conversation on its own.

from django.db import migrations

from cost_management.probe_chats import unflagged_probe_chat_ids

SEED_ENTRIES = [
    {
        "date": "2026-09-25",
        "category": "measurement_fix",
        "description": (
            "From 2026-09-09 until 2026-09-25 the AOP monitor's synthetic "
            "probe asked 'Do you have any Pokemon booster boxes in stock?' "
            "about every six minutes, each time as a new chat. After the "
            "chatbot's repeat-message breaker shipped (2026-09-17) about five "
            "an hour still got through, which flag_automated_chats did not "
            "catch (it flags more than five an hour), so they were counted "
            "as real conversations. The probe was removed and every probe "
            "chat is now flagged likely_automated: conversation counts drop "
            "for those months, and their spend moves into the bot share "
            "prorated out of cost/conversation's numerator. The ENG-149/150 "
            "'booster-box bot' of 2026-09-09 to 2026-09-13 was very likely "
            "this same probe."
        ),
    },
]


def flag_probe_chats(apps, schema_editor):
    Chat = apps.get_model("cost_management", "Chat")
    Message = apps.get_model("cost_management", "Message")
    chat_ids = unflagged_probe_chat_ids(Chat, Message)
    if chat_ids:
        Chat.objects.filter(chat_id__in=chat_ids).update(likely_automated=True)

    CostMethodologyChange = apps.get_model("cost_management", "CostMethodologyChange")
    for entry in SEED_ENTRIES:
        CostMethodologyChange.objects.get_or_create(
            date=entry["date"], description=entry["description"],
            defaults={"category": entry["category"]},
        )


def remove_seeded_changes(apps, schema_editor):
    # Flags are left in place on reverse: a chat already flagged before this
    # migration can't be told apart from one this migration flagged, and the
    # admin is where a single misclassification gets undone.
    CostMethodologyChange = apps.get_model("cost_management", "CostMethodologyChange")
    CostMethodologyChange.objects.filter(
        description__in=[e["description"] for e in SEED_ENTRIES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0015_seed_bot_proration_methodology_change"),
    ]

    operations = [
        migrations.RunPython(flag_probe_chats, remove_seeded_changes),
    ]
