# Generated by Django 5.2.8
#
# Flags any chats created during shadow testing (chat_ids containing 'shadowtest')
# as likely_automated=True, ensuring they drop out of conversation counts,
# insights generation, and the chat summary list so metrics remain untainted.

from django.db import migrations


def flag_shadowtest_chats(apps, schema_editor):
    Chat = apps.get_model("cost_management", "Chat")
    Chat.objects.filter(chat_id__icontains="shadowtest").update(likely_automated=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cost_management", "0016_flag_aop_probe_chats"),
    ]

    operations = [
        migrations.RunPython(flag_shadowtest_chats, noop_reverse),
    ]
