# Generated by Django 5.2.8 on 2026-10-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0018_attributedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('cost_per_conversation', 'Cost per conversation above $X'), ('spend_anomaly', 'Spend anomaly vs trailing baseline'), ('cache_hit_rate_drop', 'Cache savings-rate drop'), ('eval_score_drop', 'Eval score drop')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('threshold', models.FloatField()),
                ('cooldown_hours', models.IntegerField(default=24)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('breached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperatorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertFiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('headline', models.TextField()),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firings', to='cost_management.alertrule')),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
    ]
