# Generated by Django 5.2.8 on 2026-10-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0020_seed_default_alert_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id_raw', models.CharField(db_index=True, max_length=255)),
                ('shop', models.CharField(db_index=True, default='', max_length=255)),
                ('surface', models.CharField(choices=[('chat', 'Chat'), ('ai_curator', 'AI Curator')], default='chat', max_length=20)),
                ('stated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('picks', models.JSONField(default=list)),
                ('emitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_telemetry', to='cost_management.chat')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'created_at'], name='cost_manage_shop_091d4b_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_id_raw', 'surface', 'emitted_at'), name='unique_advisor_telemetry_emit')],
            },
        ),
    ]
