# Generated by Django 5.2.8 on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0021_advisortelemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='shop',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
